### PR TITLE
Add visit link to Device Info

### LINKED ISSUE #25: Please add a 'visit' link to the SmartEVSE web page
So a user can easily visit the SmartEVSE's web page.

A 'visit' link like this:
image
(Sorry I couldn't find what this link is called or how to create it.)

### PR DESCRIPTION
**Pull request by thvd**
Fixes #25

### CODE REVIEW

**Comment by dingo35** [comment]
Feel free to add this to your personal build, but it makes no sense to me adding this...

**Comment by sonar98** [comment]
@dingo35 what is the problem of adding this? This does not break anything does it? 
For me it would be a nice addition too.
To create a personal build for this would be a bit over the top.

**Comment by dingo35** [comment]
I am not sure, but looking at the code it might break backward compatibility for users who made scripts and automations?

**Comment by sonar98** [comment]
Only thing it adds is the configuration url.
I tested with my own setup and my automations are still working.

Only difference I can see is the link to visit the web interface of SmartEVSE.
image

**Pull request closed without merging**
